USE bookbazaar;

-- Statements were written by me (Ziyad) however the data itself was generated by AI as I couldn't think of it on my own.

-- CREATE 

INSERT INTO authors (first_name, last_name, nationality, bio) 
VALUES ('Agatha', 'Christie', 'British', 'British crime novelist');

INSERT INTO users (username, email, password_hash, phone_number, address) 
VALUES ('mystery_fan', 'mystery@example.com', 'hashed_pass_001', '+1-555-9999', '123 Mystery Lane');

INSERT INTO books (title, author_id, genre, edition, description, language, publication_date, price, stock_quantity) 
VALUES ('Murder on the Orient Express', 5, 'Mystery', 'Classic Edition', 'Famous detective mystery', 'English', '1934-01-01', 14.99, 5);

--READ 

SELECT title, price, stock_quantity 
FROM books 
WHERE genre = 'Fantasy';

SELECT a.first_name, a.last_name, COUNT(b.book_id) as total_books
FROM authors a
LEFT JOIN books b ON a.author_id = b.author_id
GROUP BY a.author_id, a.first_name, a.last_name;

-- UPDATE 

UPDATE books 
SET price = 16.99 
WHERE title = '1984';

UPDATE users 
SET phone_number = '+1-555-1234', address = '456 New Address St' 
WHERE username = 'johndoe';

START TRANSACTION;
UPDATE books 
SET stock_quantity = stock_quantity - 1 
WHERE book_id = 1 AND stock_quantity > 0;

INSERT INTO user_books (user_id, book_id, date_added) 
VALUES (1, 1, CURDATE());
COMMIT;

-- DELETE 

DELETE FROM user_books 
WHERE user_id = 2 AND book_id = 3;

DELETE FROM books 
WHERE stock_quantity = 0;

START TRANSACTION;
INSERT INTO users (username, email, password_hash) 
VALUES ('temp_user', 'temp@test.com', 'temp_pass');

DELETE FROM users 
WHERE username = 'temp_user';
COMMIT;

----------------------------------------------------------------------------------------------------------
SELECT 'Total Authors' as info, COUNT(*) as count FROM authors
UNION ALL
SELECT 'Total Books', COUNT(*) FROM books
UNION ALL
SELECT 'Total Users', COUNT(*) FROM users
UNION ALL
SELECT 'Total User-Book Relations', COUNT(*) FROM user_books;